name: CI

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.7.0" # Specify your Node.js version here

      - name: Install Dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm test

    deploy:
    name: Deploy to Vercel
    needs: test # This job runs only if the 'test' job succeeds
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Adjust this if you deploy from a different branch

    steps:
      - uses: actions/checkout@v2
      
      - name: Vercel Action
        uses: amondnet/vercel-action@v20
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }} # Vercel token stored in GitHub Secrets
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }} # Vercel Organization ID
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }} # Vercel Project ID



